version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - "8010:8000"
    env_file:
      - docker/dev/env/.env.dev
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/dev/env/.db.env

volumes:
  postgres_data: